# Site settings
title: PM2
email: contact@pm2.io
description: >- # this means to ignore newlines until "baseurl:"
  PM2 is an advanced production process manager for Node.js with load balancing,
  zero-downtime reload, startup scripts and monitoring.
baseurl: ""
url: "https://pm2.keymetrics.io"
repo_url: "https://github.com/pm2-hive/pm2-hive.github.io"

sass:
  sass_dir: _sass

markdown: kramdown

exclude: ['node_modules', 'scripts', 'Gemfile', 'Gemfile.lock', 'README.md', 'vendor']

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

redcarpet:
  extensions: ['tables', 'no_intra_emphasis', 'autolink']

permalink: /blog/:year/:month/:day/:title
paginate: 1
register_url: https://id.keymetrics.io/api/oauth/register

# Analytics (ported from pm2.io)
mixpanel:
  enabled: true
  token: 0abf6a940a43403982c64ed92aa398dd
  api_host: https://api-eu.mixpanel.com
  dev_mode: false # Set to true to enable debug logging and ignore DNT locally
  geo_targeting: true # Set to true enable the geo-based cookie-consent banner display
